apiVersion: v1
kind: Namespace
metadata:
  name: app-test-2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-test-2
  namespace: app-test-2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-test-2
  template:
    metadata:
      labels:
        app: app-test-2
    spec:
      containers:
        - name: app-test-2
          image: nginx:latest
          ports:
            - name: web
              containerPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: app-test-2-ingress
    namespace: app-test-2
spec:
  rules:
    - host: "127.0.0.1"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: app-test-2-svc
                port:
                  number: 80
